version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - journal-wiki-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  webapp:
    volumes:
      - ./webapp/webapp:/app
    image: journal-wiki-webapp
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: ./webapp
      dockerfile: webapp.dockerfile
    # command: bash -c "while true; do sleep 1; done" # Infinite loop to keep container live doing nothing
    command: flask run
volumes:
  journal-wiki-db-data:
