"""empty message

Revision ID: 4a27a3b3257e
Revises: f459ea95899e
Create Date: 2018-07-15 22:40:18.963408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a27a3b3257e'
down_revision = 'f459ea95899e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_plugin_preference', 'user_plugin_toggle', ['user_id', 'plugin_name'])
    op.drop_constraint('_user_plugin_name', 'user_plugin_toggle', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_plugin_name', 'user_plugin_toggle', ['user_id', 'plugin_name'])
    op.drop_constraint('_user_plugin_preference', 'user_plugin_toggle', type_='unique')
    # ### end Alembic commands ###
