"""empty message

Revision ID: 8b0d0eb14ca0
Revises: b11721c85196
Create Date: 2018-06-12 13:44:06.379935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0d0eb14ca0'
down_revision = 'b11721c85196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtg_card_fetcher_cache',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['journal_entry.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('parent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mtg_card_fetcher_cache')
    # ### end Alembic commands ###
