"""empty message

Revision ID: 29eb50bedde2
Revises: 55b237c1819c
Create Date: 2018-02-17 20:40:03.107310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29eb50bedde2'
down_revision = '55b237c1819c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('contents', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entry', 'contents')
    # ### end Alembic commands ###
