"""empty message

Revision ID: 2da871707c7f
Revises: 4093531d42dc
Create Date: 2018-06-12 12:56:11.896914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2da871707c7f'
down_revision = '4093531d42dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    op.alter_column('name_search_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('name_search_cache', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('name_search_cache', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('name_search_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('journal_entry', 'updated_at')
    
    # ### end Alembic commands ###
