"""empty message

Revision ID: 3c29565c2da0
Revises: 8b0d0eb14ca0
Create Date: 2018-06-13 00:17:43.880828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c29565c2da0'
down_revision = '8b0d0eb14ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_id_date', 'journal_entry', ['owner_id', 'create_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_id_date', 'journal_entry', type_='unique')
    # ### end Alembic commands ###
