"""empty message

Revision ID: 3c599a12b756
Revises: 3c29565c2da0
Create Date: 2018-06-15 12:24:51.108694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c599a12b756'
down_revision = '3c29565c2da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('journal_entry_owner_id_fkey', 'journal_entry', type_='foreignkey')
    op.create_foreign_key(None, 'journal_entry', 'user', ['owner_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal_entry', type_='foreignkey')
    op.create_foreign_key('journal_entry_owner_id_fkey', 'journal_entry', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
