"""empty message

Revision ID: 983ed3b059a1
Revises: b43ee08e0103
Create Date: 2018-06-11 19:14:57.361885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983ed3b059a1'
down_revision = 'b43ee08e0103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_search_cache',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('parent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name_search_cache')
    # ### end Alembic commands ###
