"""empty message

Revision ID: a5e927ad2dd2
Revises: 6927dac2a09f
Create Date: 2018-07-21 23:34:10.285505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5e927ad2dd2'
down_revision = '6927dac2a09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_output_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('plugin_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('json', sa.String(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['journal_entry.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('indexer_plugin_cache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexer_plugin_cache',
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('json', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['journal_entry.id'], name='indexer_plugin_cache_parent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', name='indexer_plugin_cache_pkey')
    )
    op.drop_table('plugin_output_cache')
    # ### end Alembic commands ###
