"""empty message

Revision ID: cda7c2a12cad
Revises: d370892489d3
Create Date: 2018-07-21 23:16:55.829351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cda7c2a12cad'
down_revision = 'd370892489d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name_search_cache')
    op.add_column('plugin_output_cache', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('plugin_output_cache', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin_output_cache', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('plugin_output_cache', 'id')
    op.create_table('name_search_cache',
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('json', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['journal_entry.id'], name='name_search_cache_parent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', name='name_search_cache_pkey')
    )
    # ### end Alembic commands ###
