"""empty message

Revision ID: d50be64bceb7
Revises: f543bf815639
Create Date: 2018-06-10 16:01:42.527153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50be64bceb7'
down_revision = 'f543bf815639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journal_entry_create_date', table_name='journal_entry')
    op.create_index(op.f('ix_journal_entry_create_date'), 'journal_entry', ['create_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entry_create_date'), table_name='journal_entry')
    op.create_index('ix_journal_entry_create_date', 'journal_entry', ['create_date'])
    # ### end Alembic commands ###
